{
 "title": "Python Metrics",
 "tags": [ "python" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Python platform information",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "targets": [
    { "expr": "python_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Objects collected during gc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (generation) (increase(python_gc_objects_collected_total[$__rate_interval]))",
     "legendFormat": "Gen {{generation}}"
    }
   ]
  },
  {
   "title": "Uncollectable objects found during GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (generation) (increase(python_gc_objects_uncollectable_total[$__rate_interval]))",
     "legendFormat": "Gen {{generation}}"
    }
   ]
  },
  {
   "title": "Number of times this generation was collected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (generation) (increase(python_gc_collections_total[$__rate_interval]))",
     "legendFormat": "Gen {{generation}}"
    }
   ]
  },
  {
   "title": "Virtual memory size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job, instance) (process_virtual_memory_bytes)",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Resident memory size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job, instance) (process_resident_memory_bytes)",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Total user and system CPU time spent in seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job, instance) (increase(process_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Number of open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job, instance) (process_open_fds)",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Percent of opened file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job, instance) (process_open_fds / process_max_fds) * 100",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  }
 ]
}